#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
gunzip -k ../data/datasets.sqlite.gz
python -u dayahead_method_comparison.py
python -u intraday_method_comparison.py
python -u mpc_demo.py
rm ../data/datasets.sqlite
